# Generated by Django 2.1.7 on 2019-03-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syn_edb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s_order',
            options={'verbose_name': 'S_Order'},
        ),
        migrations.RenameField(
            model_name='s_order',
            old_name='created',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='s_order',
            old_name='updated',
            new_name='updateTime',
        ),
    ]
