# Generated by Django 2.1.7 on 2019-03-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syn_edb', '0002_auto_20190319_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s_order',
            options={},
        ),
        migrations.AlterModelTable(
            name='s_order',
            table='S_Order',
        ),
    ]
