# Generated by Django 2.1.7 on 2019-03-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syn_edb', '0004_auto_20190323_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uorderitem',
            options={'managed': True},
        ),
    ]
